apiVersion: apps/v1
kind: Deployment
metadata:
  name: athena-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: athena-backend
  template:
    metadata:
      labels:
        app: athena-backend
    spec:
      containers:
        - name: athena-backend
          image: athena-backend:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: athena-backend-config
            - secretRef:
                name: athena-oauth-secret
          volumeMounts:
            - name: athena-data
              mountPath: /app/data
            
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      
      volumes:
        - name: athena-data
          persistentVolumeClaim:
            claimName: athena-backend-pvc