export const QUICK_QUESTIONS = {
  "Java & Core": [
    "What is dependency injection in Spring Boot?",
    "What is ACID?",
    "What is JPA?",
    "What is ORM?",
    "What is StreamAPI?",
    "What is Serialization?",
    "What is serialVersionUID?",
    "What is IOC?",
    "What is the Bean Lifecycle?",
    "What is the difference between == and equals()?",
    "What is the difference between heap and stack?",
    "What is the difference between HashMap and ConcurrentHashMap?",
    "What are Sealed Classes?",
    "Why are strings immutable?",
    "What is the difference between ArrayList and LinkedList?",
    "What is the difference between Overloading and Overriding?",
    "What is Generic and Type Erasure?",
    "What is Garbage Collection?",
    "What is Multi-threading?",
  ],

  "Spring & Microservices": [
    "What is Spring Security?",
    "What are the Java 8 features?",
    "What is the Saga Pattern?",
    "What is the Observer Pattern?",
    "What is the Factory Pattern?",
    "What is @ControllerAdvice vs @RestControllerAdvice?",
    "What is @Scope?",
    "What is the Volatile keyword?",
    "What is an API Gateway?",
    "What is the Circuit Breaker pattern?",
    "What is Service Registry?",
    "What is Service Discovery?",
    "What is Load Balancing?",
    "What is Config Server?",
    "What is Spring Cloud Bus?",
    "What is Distributed Tracing?",
    "What is Idempotency?",
    "What is Cascading?",
    "What is Feign Client implementation?",
  ],

  React: [
    "What is React JS?",
    "What is a Component?",
    "What is the difference between functional and class components?",
    "What is useState?",
    "What is useEffect?",
    "What is Virtual DOM?",
    "What is the difference between props and state?",
    "What is Component lifecycle?",
    "What is a Controlled component?",
    "What is Redux?",
    "What is Axios?",
    "What is Prop drilling?",
    "What is React Context API?",
  ],

  "Database & Messaging": [
    "How do you write queries in your project?",
    "What is Lazy Loading?",
    "What is Redis?",
    "What is Kafka?",
    "What is Elasticsearch?",
    "What is a Stored Procedure?",
    "What is Transaction Management?",
    "What is the difference between Lazy and Eager Fetching?",
  ],

  "Stream Hands-on": [
    "Word count",
    "Character count",
    "List of duplicate characters",
    "Highest salary",
    "Second highest salary",
    "Find average",
    "Find max and min",
    "Reverse words",
    "Sum of digits",
    "What is flatMap?",
    "What are Parallel Streams?",
    "What is CompletableFuture?",
  ],

  "AWS & DevOps": [
    "How was your app deployed in AWS?",
    "EC2 vs ECS vs EKS — which one would you use and why?",
    "How would you deploy a Spring Boot JAR on EC2?",
    "How does a Load Balancer distribute requests?",
    "What is Auto Scaling?",
    "What is RDS?",
    "What is S3?",
    "What is CloudWatch?",
    "How would you manage secrets?",
    "What is CI/CD?",
  ],
};
