spring.application.name=interview-preparation-bot

# Ollama
spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.model=${OLLAMA_CHAT_MODEL:qwen3:1.7b}
spring.ai.ollama.chat.think=${OLLAMA_CHAT_THINK:false}
spring.ai.ollama.chat.num-predict=${OLLAMA_CHAT_NUM_PREDICT:256}
spring.ai.ollama.chat.temperature=${OLLAMA_CHAT_TEMPERATURE:0.2}
spring.ai.ollama.embedding.model=${OLLAMA_EMBEDDING_MODEL:qwen3-embedding:0.6b}

# File Path
manifest.path=./data/document-manifest.json
vector.store.path=./data/vector-store.json
chat.history.path=./data/chat-history.json
spring.banner.location=classpath:./banner.txt

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}